### ISSUE TITLE
Adding in a smart Computer TicTacToe

### ISSUE THREAD

**Issue by lesleykhuu** [UCSB-CS56-Projects/cs56-games-rock-paper-scissors#5] opened 2014-03-07 00:34 UTC
Making a Computer that uses strategy to play against a Human. Make it actually play smart.

~requested: 200

**Comment by athielk** [comment] 2016-09-29 18:21
F16 CLOSED: duplicate of #43

**Closed by athielk** 2016-09-29 18:21 UTC
